name: Sync forward2

on:
  push:
    branches: ["main"]

jobs:
  sync:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
