name: Sync forward2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Replace
        run: |
          Get-ChildItem | Where-Object { $_ -notmatch "replace.ps1" } | ForEach-Object {
          $content = Get-Content $_
          $content = $content `
              -replace "^package forward$", "package forward2" `
              -replace '"forward"', '"forward2"'
          Set-Content -Path $_ -Value $content
          }
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: QZLin/forward2
          path: forward2
